import { Col, Row } from "react-bootstrap";
import Meals from "./Meals";

const data = [
  {
    id: 1,
    title: "Margherita Pizza",
    price: 249,
    rating: 4.5,
    image: "https://picsum.photos/seed/pizza1/400/300.jpg",
    category: "Pizza",
    description: "Classic margherita with fresh basil and mozzarella.",
  },
  {
    id: 2,
    title: "Veggie Burger",
    price: 199,
    rating: 4.2,
    image: "https://picsum.photos/seed/burger1/400/300.jpg",
    category: "Burger",
    description: "Loaded veggie burger with special sauce.",
  },
  {
    id: 3,
    title: "Chicken Burger",
    price: 229,
    rating: 4.6,
    image: "https://picsum.photos/seed/burger2/400/300.jpg",
    category: "Burger",
    description: "Juicy fried chicken patty with mayo and lettuce.",
  },
  {
    id: 4,
    title: "Paneer Tikka",
    price: 179,
    rating: 4.4,
    image: "https://picsum.photos/seed/paneer1/400/300.jpg",
    category: "Indian",
    description: "Smoky paneer cubes marinated in spices.",
  },
  {
    id: 5,
    title: "Chicken Biryani",
    price: 299,
    rating: 4.8,
    image: "https://picsum.photos/seed/biryani1/400/300.jpg",
    category: "Indian",
    description: "Aromatic basmati rice with tender chicken.",
  },
  {
    id: 6,
    title: "Veg Biryani",
    price: 249,
    rating: 4.3,
    image: "https://picsum.photos/seed/biryani2/400/300.jpg",
    category: "Indian",
    description: "Flavorful rice cooked with mixed vegetables.",
  },
  {
    id: 7,
    title: "Chocolate Donut",
    price: 79,
    rating: 4.7,
    image: "https://picsum.photos/seed/donut1/400/300.jpg",
    category: "Dessert",
    description: "Soft donut topped with rich chocolate glaze.",
  },
  {
    id: 8,
    title: "French Fries",
    price: 99,
    rating: 4.1,
    image: "https://picsum.photos/seed/fries1/400/300.jpg",
    category: "Snacks",
    description: "Crispy golden fries with salt seasoning.",
  },
  {
    id: 9,
    title: "Pasta Alfredo",
    price: 259,
    rating: 4.5,
    image: "https://picsum.photos/seed/pasta1/400/300.jpg",
    category: "Pasta",
    description: "Creamy Alfredo pasta with herbs.",
  },
  {
    id: 10,
    title: "Pasta Arrabiata",
    price: 249,
    rating: 4.3,
    image: "https://picsum.photos/seed/pasta2/400/300.jpg",
    category: "Pasta",
    description: "Spicy tomato-based pasta with chili flakes.",
  },
  {
    id: 11,
    title: "Grilled Sandwich",
    price: 149,
    rating: 4.0,
    image: "https://picsum.photos/seed/sandwich1/400/300.jpg",
    category: "Snacks",
    description: "Vegetable grilled sandwich with cheese.",
  },
  {
    id: 12,
    title: "Club Sandwich",
    price: 189,
    rating: 4.4,
    image: "https://picsum.photos/seed/sandwich2/400/300.jpg",
    category: "Snacks",
    description: "Triple-layer sandwich with mayo and veggies.",
  },
  {
    id: 13,
    title: "Chole Bhature",
    price: 159,
    rating: 4.7,
    image: "https://picsum.photos/seed/chole1/400/300.jpg",
    category: "Indian",
    description: "North Indian classic with spicy chickpeas.",
  },
  {
    id: 14,
    title: "Masala Dosa",
    price: 129,
    rating: 4.5,
    image: "https://picsum.photos/seed/dosa1/400/300.jpg",
    category: "Indian",
    description: "Crispy dosa with potato filling.",
  },
  {
    id: 15,
    title: "Idli Sambar",
    price: 99,
    rating: 4.3,
    image: "https://picsum.photos/seed/idli1/400/300.jpg",
    category: "Indian",
    description: "Soft idlis served with sambar and chutney.",
  },
  {
    id: 16,
    title: "Sushi Roll",
    price: 499,
    rating: 4.6,
    image: "https://picsum.photos/seed/sushi1/400/300.jpg",
    category: "Japanese",
    description: "Fresh salmon sushi with sticky rice.",
  },
  {
    id: 17,
    title: "Ramen Bowl",
    price: 399,
    rating: 4.7,
    image: "https://picsum.photos/seed/ramen1/400/300.jpg",
    category: "Japanese",
    description: "Rich broth ramen with veggies and egg.",
  },
  {
    id: 18,
    title: "Momos",
    price: 129,
    rating: 4.4,
    image: "https://picsum.photos/seed/momos1/400/300.jpg",
    category: "Snacks",
    description: "Steamed dumplings with spicy chutney.",
  },
  {
    id: 19,
    title: "Spring Rolls",
    price: 139,
    rating: 4.1,
    image: "https://picsum.photos/seed/rolls1/400/300.jpg",
    category: "Snacks",
    description: "Crispy rolls stuffed with vegetables.",
  },
  {
    id: 20,
    title: "Cold Coffee",
    price: 89,
    rating: 4.2,
    image: "https://picsum.photos/seed/coffee1/400/300.jpg",
    category: "Beverage",
    description: "Iced coffee with whipped cream.",
  },
  {
    id: 21,
    title: "Mango Shake",
    price: 109,
    rating: 4.6,
    image: "https://picsum.photos/seed/mango1/400/300.jpg",
    category: "Beverage",
    description: "Thick mango shake made with fresh pulp.",
  },
  {
    id: 22,
    title: "Chocolate Cake",
    price: 299,
    rating: 4.9,
    image: "https://picsum.photos/seed/cake1/400/300.jpg",
    category: "Dessert",
    description: "Soft chocolate cake with creamy frosting.",
  },
  {
    id: 23,
    title: "Ice Cream Sundae",
    price: 149,
    rating: 4.5,
    image: "https://picsum.photos/seed/sundae1/400/300.jpg",
    category: "Dessert",
    description: "Vanilla ice cream topped with chocolate.",
  },
  {
    id: 24,
    title: "Tandoori Chicken",
    price: 349,
    rating: 4.8,
    image: "https://picsum.photos/seed/tandoori1/400/300.jpg",
    category: "Indian",
    description: "Spicy grilled chicken with smoky aroma.",
  },
  {
    id: 25,
    title: "Fish Fry",
    price: 299,
    rating: 4.4,
    image: "https://picsum.photos/seed/fish1/400/300.jpg",
    category: "Seafood",
    description: "Crispy fried fish with lemon.",
  },
  {
    id: 26,
    title: "Garlic Bread",
    price: 119,
    rating: 4.3,
    image: "https://picsum.photos/seed/garlic1/400/300.jpg",
    category: "Snacks",
    description: "Toasted bread loaded with garlic butter.",
  },
  {
    id: 27,
    title: "Falafel Wrap",
    price: 199,
    rating: 4.1,
    image: "https://picsum.photos/seed/falafel1/400/300.jpg",
    category: "Middle Eastern",
    description: "Crispy falafel wrapped with veggies.",
  },
  {
    id: 28,
    title: "Shawarma",
    price: 229,
    rating: 4.7,
    image: "https://picsum.photos/seed/shawarma1/400/300.jpg",
    category: "Middle Eastern",
    description: "Juicy chicken wrapped with garlic sauce.",
  },
  {
    id: 29,
    title: "Caesar Salad",
    price: 179,
    rating: 4.2,
    image: "https://picsum.photos/seed/salad1/400/300.jpg",
    category: "Salad",
    description: "Fresh romaine with croutons and dressing.",
  },
  {
    id: 30,
    title: "Fruit Bowl",
    price: 149,
    rating: 4.3,
    image: "https://picsum.photos/seed/fruits1/400/300.jpg",
    category: "Healthy",
    description: "A refreshing mix of seasonal fruits.",
  },
];
const MealsCard = () => {
  return (
    <>
      <div className="container-fluid">
        <Row className="g-2 justify-content-between">
          {data.map((meal) => (
            <Col key={meal.id} xs={12} sm={6} md={4} lg={2}>
              <Meals key={meal.id} meal={meal} />
            </Col>
          ))}
        </Row>
      </div>
    </>
  );
};
export default MealsCard;
